Repository WildCodeSchool/tours-0320-php-rhc-cpias, pull requests merged in 2020-06, with the labels that each got.

#3 Upload csv
  config/services.yaml
  src/Controller/UploadController.php
  src/Entity/Upload.php
  src/Form/UploadType.php
  src/Migrations/Version20200604084029.php
  src/Repository/UploadRepository.php
  templates/base.html.twig
  templates/formUpload.html.twig
Labels: reviewed

#4 Formulaire ajout fichier souche
  assets/scss/_vars.scss
  assets/scss/app.scss
  composer.json
  composer.lock
  package.json
  src/Controller/StrainController.php
  src/Entity/Strain.php
  src/Form/StrainType.php
  src/Migrations/Version20200602213113.php
  src/Repository/StrainRepository.php
  symfony.lock
  templates/base.html.twig
  templates/strain/_delete_form.html.twig
  templates/strain/_form.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/new.html.twig
  templates/strain/show.html.twig
  yarn.lock
Labels: reviewed

#8 ajouter et modifier un établissement
  ,
  assets/scss/bootstrap.min.css
  src/Controller/FinessController.php
  src/Entity/Finess.php
  src/Form/FinessType.php
  src/Migrations/Version20200602213113.php
  src/Migrations/Version20200608141647.php
  src/Migrations/Version20200612093020.php
  src/Migrations/Version20200612095933.php
  src/Repository/FinessRepository.php
  templates/base.html.twig
  templates/finess/_form.html.twig
  templates/finess/edit.html.twig
  templates/finess/new.html.twig
Labels: reviewed

#9 Formulaire ajout fichier souche
  assets/js/app.js
  assets/scss/_bootswatch.scss
  assets/scss/_vars.scss
  assets/scss/app.scss
  config/packages/twig.yaml
  package.json
  src/Entity/Strain.php
  src/Form/StrainType.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/strain/_delete_form.html.twig
  templates/strain/_form.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/new.html.twig
  templates/strain/show.html.twig
  webpack.config.js
  yarn.lock
Labels: reviewed

#11 Relation Finess/Strain
  src/Entity/Finess.php
  src/Entity/Strain.php
  src/Form/StrainType.php
  src/Migrations/Version20200612093020.php
  src/Migrations/Version20200612095933.php
  templates/strain/index.html.twig
  templates/strain/show.html.twig
Labels: Waiting for review

#17 Change phpmd configuration to exclude SignalementEsin.php
  phpmd.xml
Labels: Correction done, reviewed

#16 Update FinessType.php
  src/Form/FinessType.php
Labels: reviewed

#14 Sessions utilisateur/responsable
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/security/login.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/new.html.twig
  templates/strain/show.html.twig
Labels: Correction done

#21 Carte
  templates/map/index.html.twig
Labels: reviewed

#22 Roles
  .gitignore
  config/packages/security.yaml
  src/Controller/FinessController.php
  src/Controller/StrainController.php
  src/Migrations/Version20200616121848.php
  templates/base.html.twig
  templates/finess/_form.html.twig
  templates/security/login.html.twig
  templates/strain/index.html.twig
  templates/strain/show.html.twig
Labels: reviewed

#23 Display esin
  ,
  phpmd.xml
  src/Controller/EsinController.php
  src/Controller/UploadController.php
  src/Entity/Esin.php
  src/Form/EsinType.php
  src/Migrations/Version20200617134222.php
  src/Migrations/Version20200619215616.php
  src/Migrations/Version20200622132757.php
  src/Migrations/Version20200622133053.php
  src/Repository/EsinRepository.php
  src/Repository/UploadRepository.php
  src/Service/DataRecovery.php
  templates/_navbar.html.twig
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  templates/esin/upload.html.twig
  templates/strain/new.html.twig
Labels: reviewed

#25 Petites corrections indispensables
  src/Controller/EsinController.php
  src/Entity/Esin.php
  src/Form/EsinType.php
  templates/_navbar.html.twig
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  templates/esin/upload.html.twig
Labels: reviewed

#26 Finesscontroller
  src/Controller/FinessController.php
  templates/index.html.twig
Labels: reviewed

#28 correction BDD versions
  src/Migrations/Version20200619215616.php
  src/Migrations/Version20200622132757.php
  src/Migrations/Version20200622133053.php
  src/Migrations/Version20200623140623.php
  templates/finess/index.html.twig
Labels: reviewed

#30 Carte
  public/openlayer/finessLayer.js
  src/Controller/MapController.php
  src/Form/MapSelectionType.php
  src/Migrations/Version20200619135521.php
  templates/map/index.html.twig
  templates/map/show.html.twig
Labels: reviewed
