Repository WildCodeSchool/tours-0320-php-rhc-cpias, pull requests merged in 2020-07, with the labels that each got.

#32 First user registration whith TECHNICIAN_ROLE
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/registration/first_user.html.twig
Labels: reviewed

#31 Ajout page d'acceuil, redirection vers carte et sécurisation des tout…
  config/packages/security.yaml
  src/Controller/SecurityController.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
Labels: reviewed

#34 Css carte
  assets/scss/carte.css
  public/openlayer/finessLayer.js
  src/Controller/MapController.php
  src/Form/MapSelectionType.php
  src/Model/StrainName.php
  templates/map/index.html.twig
Labels: reviewed

#40 Css carte
  assets/scss/app.scss
  assets/scss/carte.css
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  templates/finess/index.html.twig
  templates/finess/new.html.twig
  templates/map/show.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/new.html.twig
  templates/strain/show.html.twig
Labels: reviewed

#41 Fixtures strain finess
  src/DataFixtures/FinessFixtures.php
  src/DataFixtures/StrainFixtures.php
  templates/base.html.twig
  templates/footer.html.twig
Labels: reviewed

#42 Modification StrainType => bug fix
  src/Form/StrainType.php
Labels: reviewed

#43 Dev
  assets/scss/app.scss
  assets/scss/carte.css
  config/packages/security.yaml
  docker-entry.sh
  public/openlayer/finessLayer.js
  src/Controller/MapController.php
  src/Controller/RegistrationController.php
  src/Controller/SecurityController.php
  src/DataFixtures/FinessFixtures.php
  src/DataFixtures/StrainFixtures.php
  src/Entity/User.php
  src/Form/MapSelectionType.php
  src/Form/StrainType.php
  src/Form/UserType.php
  src/Migrations/Version20200706075125.php
  src/Model/StrainName.php
  src/Security/LoginFormAuthenticator.php
  symfony.lock
  templates/base.html.twig
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  templates/finess/index.html.twig
  templates/finess/new.html.twig
  templates/footer.html.twig
  templates/map/index.html.twig
  templates/map/show.html.twig
  templates/registration/first_user.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/new.html.twig
  templates/strain/show.html.twig
Labels: reviewed

#48 Ajout finess upload2
  .gitignore
  src/Controller/EsinController.php
  src/Controller/FinessController.php
  src/Entity/Esin.php
  src/Entity/Finess.php
  src/Form/EsinType.php
  src/Form/FinessType.php
  src/Migrations/.gitignore
  src/Migrations/Version20200629132048.php
  src/Migrations/Version20200706141224.php
  src/Model/Upload.php
  src/Service/DataRecovery.php
  src/Service/FindFiness.php
  templates/esin/show.html.twig
  templates/finess/upload.html.twig
Labels: reviewed

#50 Dev
  .gitignore
  docker-entry.sh
  src/Controller/EsinController.php
  src/Controller/FinessController.php
  src/Entity/Esin.php
  src/Entity/Finess.php
  src/Form/EsinType.php
  src/Form/FinessType.php
  src/Migrations/.gitignore
  src/Migrations/Version20200629132048.php
  src/Migrations/Version20200706141224.php
  src/Model/Upload.php
  src/Service/DataRecovery.php
  src/Service/FindFiness.php
  templates/esin/show.html.twig
  templates/finess/upload.html.twig
Labels: reviewed

#51 Bugfixtures
  assets/scss/app.scss
  src/DataFixtures/FinessFixtures.php
  src/Migrations/Version20200708074628.php
  templates/base.html.twig
  templates/footer.html.twig
Labels: reviewed

#52 Correction bug upload
  public/uploads/.gitignore
  src/Controller/EsinController.php
  src/Form/EsinType.php
  templates/base.html.twig
  templates/esin/upload.html.twig
Labels: reviewed

#53 Dev
  assets/scss/app.scss
  public/uploads/.gitignore
  src/Controller/EsinController.php
  src/DataFixtures/FinessFixtures.php
  src/Form/EsinType.php
  src/Migrations/Version20200708074628.php
  templates/base.html.twig
  templates/esin/upload.html.twig
  templates/footer.html.twig
Labels: reviewed

#54 Ajout de contrainte de validation NotBlank au champ finess
  src/Entity/Strain.php
Labels: MATOS qualidade, reviewed

#58 User registration
  src/Controller/RegistrationController.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: MATOS qualidade, reviewed

#60 flash message création compte utilisateur
  src/Migrations/Version20200709135607.php
  templates/security/login.html.twig
Labels: MATOS qualidade, reviewed

#61 ajout d'un accès à l'upload d'etablissements
  src/Controller/FinessController.php
  src/Entity/Esin.php
  src/Service/DataRecovery.php
  src/Service/FindFiness.php
  templates/finess/index.html.twig
Labels: MATOS qualidade, reviewed

#62 Réparation du problème d'upload pour la prod
  src/Service/DataRecovery.php
Labels: MATOS qualidade, reviewed

#63 Dev
  src/Controller/FinessController.php
  src/Entity/Esin.php
  src/Service/DataRecovery.php
  src/Service/FindFiness.php
  templates/finess/index.html.twig
Labels: reviewed

#64 correction de la PR précédente
  src/Entity/Esin.php
Labels: reviewed

#65 Dev
  docker-entry.sh
  src/Entity/Esin.php
  src/Migrations/Version20200708074618.php
  src/Migrations/Version20200708074628.php
  src/Migrations/Version20200708074718.php
  src/Migrations/Version20200713135532.php
Labels: reviewed

#68 Dev
  composer.json
  composer.lock
  config/routes.yaml
  src/Controller/FinessController.php
  src/Form/FinessType.php
  symfony.lock
  templates/finess/_form.html.twig
  templates/finess/edit.html.twig
  templates/finess/errorTemplate.html.twig
  templates/finess/errorTemplateMulti.html.twig
  templates/finess/index.html.twig
  templates/finess/show.html.twig
  templates/map/index.html.twig
Labels: MATOS qualidade, reviewed

#69 mini modif required false finesstype
  src/Form/FinessType.php
Labels: reviewed

#71 Dev
  src/Controller/FinessController.php
  src/Form/FinessType.php
  templates/finess/_form.html.twig
  templates/finess/edit.html.twig
Labels: MATOS qualidade, reviewed

#73 correction de l'upload d'établissement + modifs d'affichage sur la page
  src/Entity/Finess.php
  src/Form/FinessType.php
  src/Form/FinessUploadType.php
  src/Migrations/Version20200709135607.php
  src/Service/FindFiness.php
  templates/finess/upload.html.twig
Labels: reviewed

#75 correction migrations
  src/Migrations/Version20200709135607.php
  src/Migrations/Version20200720143542.php
Labels: reviewed

#76 Dev
  src/Entity/Finess.php
  src/Form/FinessType.php
  src/Form/FinessUploadType.php
  src/Migrations/Version20200720143542.php
  src/Service/FindFiness.php
  templates/finess/upload.html.twig
Labels: reviewed

#79 correction de la page esin/index et esin/show
  assets/scss/_bootswatch.scss
  assets/scss/esin.css
  templates/base.html.twig
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  webpack.config.js
Labels: reviewed

#80 Suppression button afficher Modification titre h1 -> Liste des souche…
  assets/scss/app.scss
  src/Controller/StrainController.php
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/show.html.twig
Labels: MATOS qualidade, reviewed

#77 test de résolution de problème pour la prod sans toucher aux fixtures
  src/Controller/RegistrationController.php
  templates/esin/upload.html.twig
  templates/finess/upload.html.twig
Labels: Correction done

#81 Dev
  assets/scss/_bootswatch.scss
  assets/scss/app.scss
  assets/scss/esin.css
  docker-entry.sh
  src/Controller/RegistrationController.php
  src/Controller/StrainController.php
  templates/base.html.twig
  templates/esin/index.html.twig
  templates/esin/show.html.twig
  templates/esin/upload.html.twig
  templates/finess/upload.html.twig
  templates/strain/edit.html.twig
  templates/strain/index.html.twig
  templates/strain/show.html.twig
  webpack.config.js
Labels: MATOS qualidade, reviewed

#82 CSS form
  Liste
  assets/scss/app.scss
  templates/registration/register.html.twig
  templates/security/login.html.twig
Labels: reviewed

#83 déplacement du flush en dehors de la boucle
  src/Service/FindFiness.php
Labels: MATOS qualidade, reviewed

#87 Finitions
  assets/scss/carte.css
  public/openlayer/css/carte.css
  public/openlayer/css/ol.css
  public/openlayer/css/ol.css.map
  public/openlayer/finessLayer.js
  src/Controller/FinessController.php
Labels: reviewed

#88 Dev
  assets/scss/carte.css
  public/openlayer/css/carte.css
  public/openlayer/css/ol.css
  public/openlayer/css/ol.css.map
  public/openlayer/finessLayer.js
  src/Controller/FinessController.php
  src/Migrations/Version20200720143542.php
  src/Migrations/Version20200728135023.php
Labels: reviewed

#89 Zoom
  README.md
  assets/scss/carte.css
  public/openlayer/finessLayer.js
Labels: Correction done

#90 Dev
  README.md
  assets/scss/carte.css
  public/openlayer/finessLayer.js
Labels: reviewed

#91 Zoom
  src/Controller/FinessController.php
Labels: reviewed

#92 Dev
  src/Controller/FinessController.php
Labels: MATOS qualidade, reviewed
